# spring configuration
spring:
   application:
      name: jblog
      
   devtools:
      livereload:
         enabled: true 
   # aop
   aop:
      auto: true
      proxy-garget-class: true

   # mvc
   mvc:
      static-path-pattern: /assets/**
      # view:
      #   prefix: /WEB-INF/views/
      #   suffix: .jsp

   #web
   web:
      resources:
         static-locations: file:/jblog-uploads/, classpath:assets/

   # message resources(i18n)
   messages:
      basename: messages/message
      encoding: utf-8
      always-use-message-format: true

   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 10MB
         
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.207:3306/jblog?charset=utf8
      username: jblog
      password: jblog
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
         
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
                    
# server configuration
server:
   port: 8088
   servlet:
      context-patch: /
      encoding: 
         charset: utf-8
         enabled: true
         
         
# logging
logging:
  config: classpath:logback.xml